name: "Build"

on:
  pull_request: {}
  push:
    branches:
      - master

permissions: {}

jobs:
  cocoapods-lint:
    name: "Cocoapods Lint"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - run: bundle install
        env:
          BUNDLE_WITHOUT: development # Stop bundler tool from installing development dependencies

      - run: bundle exec fastlane run pod_lib_lint verbose:false allow_warnings:true platforms:ios,osx,tvos

  build-and-test:
    name: "Build and Test"

    strategy:
      matrix:
        build:
          - { scheme: "iOS", os: "13", xcode: "13", swift: "5.5", build: 'platform=macOS' }
          # macOS 13
          - { scheme: "macOS", os: "13", xcode: "13", swift: "5.5", build: 'platform=macOS' }
          - { scheme: "macOS", os: "13", xcode: "13", swift: "5.6", build: 'platform=macOS' }
          - { scheme: "macOS", os: "13", xcode: "13", swift: "5.7", build: 'platform=macOS' }
          - { scheme: "macOS", os: "13", xcode: "13", swift: "5.8", build: 'platform=macOS' }
          - { scheme: "macOS", os: "13", xcode: "13", swift: "5.9", build: 'platform=macOS' }
          - { scheme: "tvOS", os: "13", xcode: "13", swift: "5.5", build: 'platform=tvOS Simulator,OS=13,name=Apple TV' }
          - { scheme: "tvOS", os: "13", xcode: "13", swift: "5.6", build: 'platform=tvOS Simulator,OS=13,name=Apple TV' }
          - { scheme: "tvOS", os: "13", xcode: "13", swift: "5.7", build: 'platform=tvOS Simulator,OS=13,name=Apple TV' }
          - { scheme: "tvOS", os: "13", xcode: "13", swift: "5.8", build: 'platform=tvOS Simulator,OS=13,name=Apple TV' }
          - { scheme: "tvOS", os: "13", xcode: "13", swift: "5.9", build: 'platform=tvOS Simulator,OS=13,name=Apple TV' }
          # macOS 12
          - { scheme: "macOS", os: "12", xcode: "12", swift: "5.5", build: 'platform=macOS' }
          - { scheme: "macOS", os: "12", xcode: "12", swift: "5.6", build: 'platform=macOS' }
          - { scheme: "macOS", os: "12", xcode: "12", swift: "5.7", build: 'platform=macOS' }
          - { scheme: "macOS", os: "12", xcode: "12", swift: "5.8", build: 'platform=macOS' }
          - { scheme: "macOS", os: "12", xcode: "12", swift: "5.9", build: 'platform=macOS' }
          - { scheme: "tvOS", os: "12", xcode: "12", swift: "5.5", build: 'platform=tvOS Simulator,OS=12,name=Apple TV' }
          - { scheme: "tvOS", os: "12", xcode: "12", swift: "5.6", build: 'platform=tvOS Simulator,OS=12,name=Apple TV' }
          - { scheme: "tvOS", os: "12", xcode: "12", swift: "5.7", build: 'platform=tvOS Simulator,OS=12,name=Apple TV' }
          - { scheme: "tvOS", os: "12", xcode: "12", swift: "5.8", build: 'platform=tvOS Simulator,OS=12,name=Apple TV' }
          - { scheme: "tvOS", os: "12", xcode: "12", swift: "5.9", build: 'platform=tvOS Simulator,OS=12,name=Apple TV' }

    # Label the job with the platform, Xcode version, and Swift version
    name: ${{ matrix.build['scheme'] }} ${{ matrix.build['os'] }} (Xcode ${{ matrix.build['xcode'] }}, Swift ${{ matrix.build['swift'] }})

    # Run the job on macOS
    runs-on: macos-${{ matrix.build['os'] }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      - run: swift lint  --parallel --configuration .swiftlint.yml -r .

      - run: xcodebuild clean test -scheme 'Auth0.${{ matrix.xcodebuild['scheme'] }}' -destination '${{ matrix.xcodebuild['build'] }}' --workspace Auth0.xcworkspace Auth0.xcodeproj
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - run: swift test --enable-code-coverage
